[package]
name = "zealot-server"
version.workspace = true
edition.workspace = true
# license.workspace = true

[dependencies]
zealot-domain = {path = "../../crates/zealot-domain"}
zealot-api = {path = "../../crates/zealot-api"}
zealot-app = {path = "../../crates/zealot-app"}
zealot-infra = {path = "../../crates/zealot-infra"}
zealot-lua   = {path = "../../crates/zealot-lua"}
tokio.workspace = true
sqlx.workspace = true
croner.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
chrono.workspace = true
uuid.workspace = true
tar = "0.4"
flate2 = "1"
