[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
rusqlite = {version = "*", features = ["bundled"]}
common = { path = "../common" }
once_cell = "1"
directories = "5"
serde = "*"