services:
  server:
    image: registry.alexanderfarrell.net/zealotd:v0.1.0
    build:
      context: ..
      dockerfile: apps/server/Dockerfile

  web:
    image: registry.alexanderfarrell.net/zealot-web:v0.1.0
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
